### PR TITLE
Do a much more thorough job with item times

### LINKED ISSUE #724: datetimes not inserted with item creation
**Describe the bug**

https://github.com/azavea/franklin/pull/630 pulled out and indexed the datetime fields of items. That's great, but for new items, we don't actually insert those fields 🤦🏻‍♂️ (and we sensibly don't fall back to item properties). This can lead to surprising behavior, where you query for items that definitely match your datetime query, and you don't get any back.

**Expected behavior**
In import and item POST, those fields should be populated

**Additional context**
We could do this quick and dirty but I'd rather not -- instead, since we know things about datetime being required, we should do the ADT thing from https://github.com/azavea/stac4s/issues/120#issuecomment-809713114 and handle the insert accordingly

### PR DESCRIPTION
**Pull request by jisantuc**
## Overview

This PR makes a few changes now that `stac4s` models datetimes better:

- it updates the `datetime`, `start_datetime`, and `end_datetime` fields as appropriate on item insert, bulk insert, and update
- it updates the filter generators to test item search behavior
- it fixes a bug I didn't know about where search datetime filters were only checking the `datetime` column
- it significantly improves test coverage for search filter + item time interactions

### Checklist

- [x] New tests have been added or existing tests have been modified

### Notes

CI is gonna fail until the stac4s release that just happened is resolvable in Maven. Might be soon.

### Testing Instructions

- import a catalog on a fully up-to-date Franklin that's already been migrated
- do some time filtering
- everything should work as you expect
- everything else is exercised by tests

Closes #724

### CODE REVIEW

**Comment by jisantuc** [comment]
ha I assumed these failures were all because 0.4.0 of stac4s wasn't available yet oops. ANYWAY 🤞🏻 for this one

File: application/src/main/scala/com/azavea/franklin/crawler/CatalogStacImport.scala [hunk 1]
```diff
@@ -153,7 +153,7 @@ class CatalogStacImport(val catalogRoot: String) {
                       )
                     ),
                     ().asJsonObject,
-                    forItem.properties,
+                    forItem.properties.asJson.asObject.getOrElse(JsonObject.empty),
```
Comment (pomadchin) [inline application/src/main/scala/com/azavea/franklin/crawler/CatalogStacImport.scala:156]: Ouf, I also don't know how to handle it better.

File: application/src/main/scala/com/azavea/franklin/database/Filterables.scala [hunk 2]
```diff
@@ -18,11 +18,13 @@ trait FilterHelpers {
...
-          Some(fr"(datetime >= $start AND datetime <= $end)")
+          Some(
+            fr"(datetime >= $start AND datetime <= $end) OR (start_datetime >= $start AND end_datetime <= $end)"
+          )
         case Some(start) :: _ =>
-          Some(fr"datetime >= $start")
+          Some(fr"(datetime >= $start OR start_datetime >= $start)")
         case _ :: Some(end) :: _ =>
-          Some(fr"datetime <= $end")
+          Some(fr"(datetime <= $end OR end_datetime <= $end)")
```
Comment (pomadchin) [inline application/src/main/scala/com/azavea/franklin/database/Filterables.scala:27]: Nice catch!

**Review by pomadchin — APPROVED** [review]
💯

File: application/src/main/scala/com/azavea/franklin/crawler/CatalogStacImport.scala (hunk 1 above)
Comment (jisantuc) [reply application/src/main/scala/com/azavea/franklin/crawler/CatalogStacImport.scala:156]: Yeah I spent about four seconds adding an `Encoder.AsObject` in `stac4s` but decided not to -- it's not hard but it didn't seem important enough
